Crjvm205
green-code-initiative/ecoCode pull request #122
Opened 2023-04-05 15:26 UTC by AntoineMeheut

CRJVM205 - Force the use of FetchType LAZY on collections in Entity JPA

- Team: 17%
- Analyzed language: java
- Implemented rule: search in the java code for FetchTypes for which the developer has not set LAZY in order to avoid unnecessarily loading data clusters into memory.
- Result of this rule: reduce the amount of useless data loaded into memory, to reduce the consumption of RAM and therefore of electricity.
- Unit tests: passed
- Definition of done : test in sonarqube passed with ecoCode-java-test-project and we did a merge request of the tests in ecoCode-java-test-project 

Pitch : Consider using LAZY mode on your FetchType for collections in JPA type entities. This will reduce the amount of data loaded into memory. And having less data loaded into memory reduces power consumption. Any electricity not produced is good for our planet.

2023-04-05 16:51 UTC, dedece35 commented
Hi @AntoineMeheut,
please modify your code to correct Unit Tests :p (maybe not already launched locally :p )

please logs of checks of you PR : 
`Error:    JavaCheckRegistrarTest.checkNumberRules:35 
Expected size: 19 but was: 20 in:...`

then I will review your code

thx

2023-04-05 16:54 UTC, dedece35 requested changes
Hi @AntoineMeheut,
please modify your code to correct Unit Tests :p (maybe not already launched locally :p )

please logs of checks of you PR :
`
Error:    JavaCheckRegistrarTest.checkNumberRules:35
Expected size: 19 but was: 20 in:...
`

then I will review your code

thx

2023-04-05 19:28 UTC, AntoineMeheut commented
Sorry, but we didn't see in the rules that we had to increment the number of rules in this control, it's done

2023-04-06 13:02 UTC, MP-Aubay commented
Just for information, 3 PR on the same rule : 
https://github.com/green-code-initiative/ecoCode/pull/125
https://github.com/green-code-initiative/ecoCode/pull/155

2023-04-06 13:42 UTC, dedece35 requested changes

2023-04-07 10:11 UTC, dirdr commented on java-plugin/src/main/java/fr/greencodeinitiative/java/checks/ForceUsingLazyFetchTypeInJPAEntity.java
> +@Rule(key = "EC80", name = "Developpement",
We followed the existent pattern, which is to hard code the rule ID into the key string. Does this need to be re implemented ?

2023-04-07 10:26 UTC, dirdr reviewed
required changes were made

2023-04-07 10:26 UTC, dirdr commented on java-plugin/src/main/java/fr/greencodeinitiative/java/checks/ForceUsingLazyFetchTypeInJPAEntity.java
> +        List<AnnotationTree> annotations = variableTree.modifiers().annotations();
After searching, ModifiersTree is not annotated @Nullable. Accessing annotations by this interface method is normally safe, so no intermediate checks are required.

2023-05-09 13:53 UTC, dedece35 commented on java-plugin/src/main/java/fr/greencodeinitiative/java/checks/ForceUsingLazyFetchTypeInJPAEntity.java
> +@Rule(key = "EC80", name = "Developpement",
no. you can give it like that

2023-05-09 13:55 UTC, dedece35 commented
Hi @dirdr,
please take into account remaining review notes and correct the code small raised by sonarcloud.io
thank you.

2023-05-17 06:42 UTC, dirdr commented
code review fix ok

2023-06-27 08:17 UTC, dirdr commented
Any news ?

2023-07-03 13:51 UTC, dedece35 commented
Hi @dirdr,
no, I didn't work on this PR, sorry. Once current task is over, this is my next priority ... with two others CRJVM205 JIRAs :p

2023-09-22 14:52 UTC, dedece35 commented
Hi @dirdr,
sorry there is another conflict to resolve, please.
and then, check DoD list here : https://github.com/green-code-initiative/ecoCode-common/blob/main/doc/starter-pack.md#definition-of-done-of-a-pr

2023-12-15 15:26 UTC, dedece35 requested changes

2023-12-15 15:26 UTC, dedece35 commented on java-plugin/src/main/java/fr/greencodeinitiative/java/checks/ForceUsingLazyFetchTypeInJPAEntity.java
> +    private void performsCheck(Arguments arguments, AnnotationTree annotationTree, Tree tree) {
here, no need to give `arguments` as input parameter because it already is present inside  `annotationTree` input parameter

2023-12-15 15:26 UTC, dedece35 commented on java-plugin/src/main/java/fr/greencodeinitiative/java/checks/ForceUsingLazyFetchTypeInJPAEntity.java
> +@Rule(key = "EC80", name = "Developpement",
there is a new way to declare configuration of one rule : please see other rules as example

2023-12-15 15:26 UTC, dedece35 commented on java-plugin/src/main/resources/fr/greencodeinitiative/l10n/java/rules/java/EC80.json
> +    "title": "Force the use of FetchType LAZY on collections in Entity JPA",
now, it isn't the good way to declare rule properties but inside `ecocode-rules-specifications` (please see another rule as example)

2023-12-15 15:26 UTC, dedece35 commented on java-plugin/src/test/files/ForceLazyFetchTypeUseAllInOne.java
> +
please as a new use case with default value for fetch keywork (thus, without "fetch" variable assigned)

2023-12-15 15:26 UTC, dedece35 commented on java-plugin/src/test/files/ForceLazyFetchTypeUseAllInOne.java
> +
why don't you give all use cases in a single file ? why several test files ?

2023-12-15 15:26 UTC, dedece35 commented on java-plugin/src/test/java/fr/greencodeinitiative/java/JavaCheckRegistrarTest.java
> +        assertThat(context.checkClasses()).hasSize(20);
maybe value has to be changed. to recheck locally, please

2023-12-15 15:29 UTC, dedece35 commented
PR on java-test-project : https://github.com/green-code-initiative/ecoCode-java-test-project/pull/5

2024-01-01 21:44 UTC, dedece35 commented
to discuss in core-team :

- good argument to prove it's a "green" rule
- no native Sonarqube rule found 

but I think we can't force developers not to use EAGER key word if they really need it.

do we refuse this rule or not ?

2024-01-03 07:04 UTC, jhertout commented
Hello,

we do not force the user to not use "EAGER", it is just a code smell. He can always ignore it. The true question is, when we use JPA entities, is the "EAGER" keyword a classic use? If in 90% of the case its use is justified may be we should not raise the code smell to avoid to pollute the analysis.
However, I think this rule is specific enough to not raise too much (not like a  problem we had with a rule on Exceptions) and I think it is not a bad thing to throw the code smell because as I understand the rule, the usage of "EAGER" must be done in specific justified cases.

2026-08-07 08:33 UTC, dedece35 commented
Hi @AntoineMeheut, @dirdr , @jhertout 

several PR have worked on this same subject (FetchType Lazy instead of Eager for OneToMany et ManyToMany relations).

After worked on a complete analysis to check if this rule is relevant : 
- first, I found that the rule already exists in SonarQube as a built-in rule : S6904
- secondly, no proof was found to check relevancy
- thirdly, I decided to launch an analysis with EnergyTracer tool which can do real measures

Thus I created a new PR to : 
- add this analysis
- clean all old references to this same subject

Here is the PR : https://github.com/green-code-initiative/creedengo-rules-specifications/pull/487

Sorry, but I have to close this PR.
thank you for the work.

2026-08-07 08:33 UTC, closed without merging