Upgrade some versions + sonar version from 9.3 to 9.8
green-code-initiative/ecoCode pull request #15
Opened 2022-12-14 13:57 UTC by oussamaLaribi

2022-12-14 14:35 UTC, dedece35 commented
Hi @oussamaLaribi,
i've just made a review with some questions. please see them.
another question / note : 
- do you run tests locally ? unit tests and manual tests with integration of plugin in a old SonarQube like a 9.3 version ? (to verify compatibility)
- I've just corrected a mistake in build github worklfow on main branch (during repository migration, I disabled build&analyse phase because of sonarQube secrets not ready) : I've just enabled again a build&test phase in build github workflow, I relaunch the worklow for your branch to check my correction with your branch, but your banch is not up-to-date ... could you upgrade your branch and commit again something to run the workflow automatically please ?

2022-12-14 14:52 UTC, oussamaLaribi commented
> Hi @oussamaLaribi, i've just made a review with some questions. please see them. another question / note :
> 
> * do you run tests locally ? unit tests and manual tests with integration of plugin in a old SonarQube like a 9.3 version ? (to verify compatibility)
> * I've just corrected a mistake in build github worklfow on main branch (during repository migration, I disabled build&analyse phase because of sonarQube secrets not ready) : I've just enabled again a build&test phase in build github workflow, I relaunch the worklow for your branch to check my correction with your branch, but your banch is not up-to-date ... could you upgrade your branch and commit again something to run the workflow automatically please ?
> * next step will be to report this sonarQube upgrade to ecocode-mobile, please

Hi @dedece35, thanks for the review.
Yes, I did those local tests.
I upgraded my branch also. It's up to date now.
Next, I will report this sonarQube upgrade to ecocode-mobile.

2022-12-14 15:07 UTC, dedece35 commented
@oussamaLaribi ok for new workflow with build&test phase.
but you don't take into account my 3 pending review comments 😜 : please see above.

2022-12-14 15:18 UTC, oussamaLaribi commented
> @oussamaLaribi ok for new workflow with build&test phase. but you don't take into account my 3 pending review comments 😜 : please see above.

@dedece35 I can't find these pending review comments

2022-12-14 15:41 UTC, dedece35 commented
@oussamaLaribi, sorry, my bad, I forget to submit my review :p : done.
now, if SonarQube 9.4 is required, I think you have to mention it in installation documentation.

2022-12-14 15:47 UTC, oussamaLaribi commented on pom.xml
> +			<scope>compile</scope>
When I delete the scope I got "package org.sonar.api.internal does not exist" I don't know why.

2022-12-14 15:49 UTC, oussamaLaribi commented on python-plugin/pom.xml
> +            <scope>compile</scope>
The same thing, when I delete the scope I got "package org.sonar.api.internal does not exist" I don't know why.

2022-12-14 15:54 UTC, oussamaLaribi commented
> @oussamaLaribi, sorry, my bad, I forget to submit my review :p : done. now, if SonarQube 9.4 is required, I think you have to mention it in installation documentation.

@dedece35 Okay, I'll mention it. Thanks

2022-12-14 16:47 UTC, dedece35 commented on python-plugin/src/main/java/fr/cnumr/python/RulesList.java
> +/*
... and java :p

2022-12-14 16:51 UTC, dedece35 commented on pom.xml
> +			<scope>compile</scope>
I will do tests to check the problem i you want

2022-12-14 16:51 UTC, oussamaLaribi commented on python-plugin/src/main/java/fr/cnumr/python/RulesList.java
> +/*
In java, we already have externalizing.

2022-12-14 16:53 UTC, oussamaLaribi commented on pom.xml
> +			<scope>compile</scope>
Okay, thanks.

2022-12-14 16:53 UTC, oussamaLaribi commented on python-plugin/pom.xml
> +            <scope>compile</scope>
Okay, thanks.

2022-12-15 09:42 UTC, dedece35 approved these changes

2022-12-15 13:50 UTC, dedece35 commented
Hi @oussamaLaribi ,
I made few minutes ago a refactoring / optimization on `pom.xml` files : there were some mistakes on scopes on dependencies.
Please, update your branch with my modifications. I think you will have some conflicts, be carefull.

Then you can delete "<scope>compile</scope>" because it is the default scope on your dependency `sonar-plugin-api-impl`

2022-12-15 13:54 UTC, oussamaLaribi commented
> Hi @oussamaLaribi , I made few minutes ago a refactoring / optimization on `pom.xml` files : there were some mistakes on scopes on dependencies. Please, update your branch with my modifications. I think you will have some conflicts, be carefull.
> 
> Then you can delete "compile" because it is the default scope on your dependency `sonar-plugin-api-impl`

Hi @dedece35, Okay I'll do it. Thanks.

2022-12-15 18:46 UTC, dedece35 commented
@oussamaLaribi, I can help if you need. tell me if you want some help.

2022-12-16 19:51 UTC, dedece35 commented
hi @oussamaLaribi , do you want to say java plugin instead ? because there is compilation failure on java plugin class.
tell me if you want some help.

2022-12-16 20:22 UTC, oussamaLaribi commented
> hi @oussamaLaribi , do you want to say java plugin instead ? because there is compilation failure on java plugin class. tell me if you want some help.

Hi @dedece35, you can check now the compilation failure on the python plugin class.

2022-12-16 23:39 UTC, dedece35 commented
@oussamaLaribi 
I made the correctino of th problem : several problems on `pom.xml` files
I made a temporary PR for you to check my modifications : please take into account all modifications on all `pom.xml` files
Problem was mainly in versions of python /php plugins.
I checked locally : 
- compilation
- package building
- deploy and execution of JAR plugins on a dockerized SonarQube

2022-12-19 08:38 UTC, oussamaLaribi commented
> @oussamaLaribi I made the correction of the problem : several problems on `pom.xml` files I made a temporary PR #20 for you to check my modifications : please take into account all modifications on all `pom.xml` files : check commit [565dd48](https://github.com/green-code-initiative/ecoCode/commit/565dd483f368ab9ac248996ae8def5080f8b5dde) Problem was mainly in versions of python / php plugins. I checked locally :
> 
> * compilation
> * package building
> * deploy and execution of JAR plugins on a dockerized SonarQube

Hi @dedece35, Okay I'll check it. Thanks.

2022-12-21 23:05 UTC, dedece35 commented
Hi @oussamaLaribi 
is it all ok for you thus I can do again a complete review ?

2022-12-22 08:18 UTC, oussamaLaribi commented
> Hi @oussamaLaribi is it all ok for you thus I can do again a complete review ?

Hi @dedece35 Yes, just the commented  <!-- <requirePlugins>java:${sonarjava.version}</requirePlugins> -->. I can't find another way to force it, in the official doc there is nothing.

2022-12-22 22:14 UTC, dedece35 commented on pom.xml
> +				<scope>compile</scope>
please, delete this scope. no need to specify it. I tested locally without it and it's ok.

2022-12-22 22:14 UTC, dedece35 commented on pom.xml
> +				<scope>compile</scope>
please, delete this scope. no need to specify it. I tested locally without it and it's ok.

2022-12-22 22:14 UTC, dedece35 commented on python-plugin/src/main/java/fr/cnumr/python/RulesList.java
> +/*
ok

2022-12-22 22:14 UTC, dedece35 commented on python-plugin/pom.xml
> +                <version>${maven-shade-plugin.version}</version>
please move this version management to root `pom.xml` file
1 - put these lines in root `pom.xml` file (in `pluginManagement` part like other maven plugins)
`
<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>${maven-shade-plugin.version}</version>
</plugin>
`
2 - delete in each langage module the line with de "version"

2022-12-22 22:14 UTC, dedece35 commented on python-plugin/pom.xml
> +                <groupId>org.apache.maven.plugins</groupId>
due to the use of this maven plugin, some xml files appears (like `java-plugin/dependency-reduced-pom.xml` for example), please add this line to `.gitignore` file :
`dependency-reduced-pom.xml`

2022-12-22 22:18 UTC, dedece35 requested changes
@oussamaLaribi , i've just made a new review. I put here somme new comments.
cheers, it's almost done :p

2022-12-23 08:51 UTC, oussamaLaribi commented
> new review

Hi @dedece35, it's done. Thanks.

2022-12-23 20:24 UTC, dedece35 commented on INSTALL.md
> +- SonarQube 9.4 or higher
done

2022-12-23 20:24 UTC, dedece35 commented on docker-compose.yml
> +    image: sonarqube:9.7-community
done

2022-12-23 20:24 UTC, dedece35 commented on docker-compose.yml
> +#     - type: bind
done

2022-12-23 20:25 UTC, dedece35 commented on python-plugin/pom.xml
> +                <groupId>org.apache.maven.plugins</groupId>
done

2022-12-23 20:26 UTC, dedece35 commented on pom.xml
> +				<scope>compile</scope>
done

2022-12-23 20:26 UTC, dedece35 commented on python-plugin/pom.xml
> +                <version>${maven-shade-plugin.version}</version>
done

2022-12-23 20:26 UTC, dedece35 commented on pom.xml
> +				<scope>compile</scope>
done

2022-12-23 21:13 UTC, dedece35 approved these changes
I check again and test again localy with all your last modifications.
It's now ok : you can merge your branch.

Another thing with minor priority, there is WARNINGs during build process in the console (`tool_build.sh` file execution).
After SonarQube has been started, plugins are ok regarding logs, but I think we have to find a solution to correct those Warnings during build phase. This problem is due to `maven-shade-plugin` added. Check capture above : 
<img width="1321" alt="Capture d’écran 2022-12-23 à 22 08 49" src="https://user-images.githubusercontent.com/12011401/209405897-3c5c2467-9bf3-4442-84dc-1d8e66b67067.png">

2022-12-25 22:35 UTC, merged

2022-12-25 22:36 UTC, dedece35 commented
Hi @oussamaLaribi, I've just merged your PR and check in main branch.

2022-12-26 08:39 UTC, oussamaLaribi commented
> Hi @oussamaLaribi, I've just merged your PR and checked in main branch again (all is ok). Please report all last modifications to `ecocode-mobile` repository and make me reviewer
Hi @dedece35, Okay I'll do it. Thanks.