feat: Avoid spring repository call in stream (#CRJVM208)
green-code-initiative/ecoCode pull request #151
Opened 2023-04-06 10:11 UTC by augustinde

2023-04-06 10:59 UTC, cyChop commented
Issue #112

2023-04-06 12:42 UTC, augustinde commented
Team 800Kg / Air France

2023-04-16 19:35 UTC, dedece35 commented
Hi @augustinde,
why do you close your PR ? because of duplication with #157 ?
if yes, do you really check #157 modifications compared to your modifications ?

According to me, when there are several issues / PRs on the same subject, I review all of them and then I choose the most accurate and then discuss with all contributors about their PR.

2023-04-17 20:45 UTC, dedece35 requested changes

2023-04-17 20:45 UTC, dedece35 commented on java-plugin/src/main/resources/fr/greencodeinitiative/l10n/java/rules/java/EC_CRJVM208.json
> +    "bug",
please remove "bug" because it isn't a bug :p

2023-04-17 20:45 UTC, dedece35 commented on java-plugin/src/main/java/fr/greencodeinitiative/java/checks/AvoidSpringRepositoryCallInLoopWithStream.java
> +    private static final MethodMatchers FOREACH_METHOD = MethodMatchers.create().ofSubTypes(BASE_STREAM).names("forEach", "forEachOrdered", "map", "peek").withAnyParameters().build();
are you sure that the list of loop methods is exhaustive ?

2023-04-17 20:45 UTC, dedece35 commented on java-plugin/src/main/java/fr/greencodeinitiative/java/RulesList.java
> +import fr.greencodeinitiative.java.checks.*;
please don't use wildcard instead of each import

2023-04-17 20:45 UTC, dedece35 commented on java-plugin/src/test/files/AvoidSpringRepositoryCallInLoopWithStream.java
> +public class AvoidSpringRepositoryCallInLoopWithStream {
please add a passing unit test with stream to check if all is ok

2023-04-17 20:45 UTC, dedece35 commented on java-plugin/src/test/files/AvoidSpringRepositoryCallInLoopWithStream.java
> +package fr.greencodeinitiative.java.checks;
please add this kind of test file in java-test-project repository (which is a independent test project to verify all is ok when the full system is deployed locally)

2023-04-17 20:45 UTC, dedece35 commented on java-plugin/src/main/java/fr/greencodeinitiative/java/checks/AvoidSpringRepositoryCallInLoopWithStream.java
> +        key = "EC_CRJVM208",
please add a new line with this id in `RULES.md` file (just next to the one talking about spring repository in loops)
please add a new entry in `CHANGELOG.md` file

2023-04-18 07:10 UTC, MP-Aubay commented
I was wondering, should this issue create a new rule class or should it update the existing AvoidSpringRepositoryCallInLoopCheck ?

To go further, we could wondering if this could be merge in AvoidSQLRequestInLoop, as the concept is the same.

2023-04-23 20:59 UTC, dedece35 commented
Hi @MP-Aubay,

I agree with you.
what do you think about it, @green-code-initiative/core team ?

2023-05-09 12:59 UTC, dedece35 commented
Hi @augustinde,

please take into account review notes and correct the smell code raised by sonarcloud.io

2023-06-28 08:09 UTC, augustinde commented
Hello, I will update this PR at the end of the week

2023-10-27 16:07 UTC, dedece35 commented
I close this PR because of stale status.
I decided to create a new PR #238 to merge code of this PR (#151) and #157 one with also some improvements : check content of #238

2023-10-27 16:07 UTC, closed without merging