[Ec2][Python][5R] Multiple if-else statement
green-code-initiative/ecoCode pull request #159
Opened 2023-04-06 13:00 UTC by eliottlv

Issue #142

2023-04-09 20:00 UTC, dedece35 requested changes
please add also updates with this rule implementation : 
- [`CHANGELOG.md`](https://github.com/green-code-initiative/ecoCode/blob/main/CHANGELOG.md) : add issue link
- [`RULES.md`](https://github.com/green-code-initiative/ecoCode/blob/main/RULES.md) : change icon

another modification to do : add a tests in [ecoCode-python-test-project](https://github.com/green-code-initiative/ecoCode-python-test-project) ==> please check others tests and make the same. as you can see test files are quite identical to unit test resources files

please make corrections on code smell problems (sonarcloud report)

2023-04-09 20:00 UTC, dedece35 commented on python-plugin/src/test/resources/checks/avoidUsingMultipleIfElseStatement.py
> +    def method_with_one_if_else_if():
add new test with `if` and `else` separated instead of `elif`

2023-04-28 09:36 UTC, Affadine commented
Match/case statement is not a performance tool although it is useful for pattern matching. For example if you need a first element test that needs to be type error proof and empty list proof, it seems that using a pattern match is faster than the semantically equivalent if block.
The multiple if else is faster for simple conditions but match/case is more beautiful, and for multiple checks, will be a clear winner.

2023-05-03 20:11 UTC, dedece35 commented
Hi @Affadine,
thank you for explanations. I agree with you, that's why the message of this rule present on `DESCRIPTION` variable explain us that isn't mandatory adn user can give its multiple if/else if wanted (for this, a `NOSONAR` could be appended to ignored error).
If you check the pythin test file, in that case, the match/case is preferred to multiple if/else.

@eliottlv, could you make review modifications to merge this PR, please ?
thank you.

2023-06-12 21:25 UTC, dedece35 commented
waiting for #200 (upgrade test cases)

2023-08-05 21:51 UTC, dedece35 commented
- #200 now ok with PHP
- new PR for python in new python repository `ecoCode-python` in PR https://github.com/green-code-initiative/ecoCode-python/pull/1
- new PR for specifications in PR https://github.com/green-code-initiative/ecoCode/pull/215

2023-08-05 21:52 UTC, closed without merging