Correct several bugs in java-plugin
green-code-initiative/ecoCode pull request #18
Opened 2022-12-16 16:17 UTC by laurentgoncalves

I found several exceptions in the java-plugin code when running it on my java code.
Here are the corrections without functional modification, just avoiding exceptions and errors

2022-12-16 20:06 UTC, dedece35 requested changes

2023-02-17 14:22 UTC, laurentgoncalves commented on java-plugin/src/test/files/OptimizeReadFileExceptionCheck.java
> +	protected String getMessageFrom(final String value) {
This method doesn't specifically need to be protected, it's here to show the bug corrected by this pull request

2023-02-17 14:23 UTC, laurentgoncalves commented on java-plugin/src/test/files/AvoidGettingSizeCollectionInLoopWhileGood.java
> +    public void badLoop()
yes you're right

2023-02-17 14:24 UTC, laurentgoncalves commented on java-plugin/src/test/files/AvoidGettingSizeCollectionInLoopWhileBad.java
> +    AvoidGettingSizeCollectionInLoopBad() {
yes, also right, since these classes are not compiled and serve only to provide text for sonar analysis I didn't get any error

2023-02-19 11:03 UTC, dedece35 commented
hello @laurentgoncalves ,

please make corrections to resolve conflicts please.

2023-03-28 13:53 UTC, laurentgoncalves commented
The code in the main branch appears to contain the same fixes as my pull request, so it is better to close it, I will run tests on the master branch and, eventually, post a new pull request

2023-03-28 13:53 UTC, closed without merging