Feature/issue 208  better build
green-code-initiative/ecoCode pull request #213
Opened 2023-07-21 23:21 UTC by jycr

fix #208

2023-09-22 09:31 UTC, dedece35 commented
Hi @jycr,
sorry but we have to discuss about this feature because I don't know it and I have some questions.

2023-10-22 15:49 UTC, jycr commented
> Hi @jycr, sorry but we have to discuss about this feature because I don't know it and I have some questions.

No problem to discuss it together.
But we can wait to split `java-plugin` into its own repo before finishing this PR?

2023-10-22 20:02 UTC, dedece35 commented
> > Hi @jycr, sorry but we have to discuss about this feature because I don't know it and I have some questions.
> 
> @dedece35: No problem to discuss it together. But we can wait to split `java-plugin` into its own repo before finishing this PR?

@jycr ... yes I think we should wait automatic release PR before merging this one

2024-10-04 13:36 UTC, dedece35 submitted a review, later dismissed

2024-10-11 16:06 UTC, dedece35 requested changes

2024-10-18 08:30 UTC, dedece35 requested changes
add an update in CHANGELOG.md, please

2024-10-18 13:17 UTC, jycr commented on .mvn/extensions.xml
> +		<version>9.6.5</version>
I have updated all Maven dependencies/plugins

2024-10-18 13:19 UTC, jycr commented
> add an update in CHANGELOG.md, please

I [have added](https://github.com/green-code-initiative/ecoCode/pull/213/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR14-R16):

> [#208](https://github.com/green-code-initiative/ecoCode/issues/208) Improves build process with [Maven Wrapper](https://maven.apache.org/wrapper/) and simplifies release management (now, just need to do a build on a tag checkout).
> If you have difficulties on some IDEs (like IntelliJ IDEA), you can follow the procedure: [configuration for Multi Modules Project](https://github.com/qoomon/maven-git-versioning-extension?tab=readme-ov-file#intellij---multi-modules-projects)

Do you need me to add any further details?

2024-10-18 13:26 UTC, dedece35 approved these changes

2024-10-18 13:28 UTC, merged