[EC63] UnnecessarilyAssignValuesToVariables rule on caught exception
green-code-initiative/ecoCode pull request #230
Opened 2023-10-06 14:54 UTC by natixis-caen

Stop to mark unused exception variables as code smell.

2023-10-20 07:25 UTC, natixis-caen commented
Hi @dedece35 , I checked the list and this PR should be ok regarding the criteria.

2023-10-20 07:40 UTC, utarwyn reviewed
LGTM 👌 Can you update the CHANGELOG?

2023-10-20 08:57 UTC, utarwyn approved these changes

2023-11-08 22:06 UTC, dedece35 requested changes

2023-11-08 22:06 UTC, dedece35 commented on java-plugin/src/test/files/UnnecessarilyAssignValuesToVariablesTestCheck.java
> +    public void testCompliantCatchException() throws Exception {
ok for me, but, please remove "throws Exception" because no Exception really thrown.

2023-11-10 21:00 UTC, dedece35 commented on java-plugin/src/test/files/UnnecessarilyAssignValuesToVariablesTestCheck.java
> +    public void testCompliantCatchException() throws Exception {
@natixis-caen : last modification , then I will approve this PR :p

2023-12-01 21:33 UTC, dedece35 commented
To discuss in core-team : deprecation of this rule only for Java

2023-12-09 22:51 UTC, dedece35 commented
Hi @utarwyn, @glalloue, @jhertout,

after checking completyly this rule (currently, only implemented in JAVA), you're right @utarwyn, there is already 2 native SonarQube rules for 2 subjects "unused variable" and "return directly instead of creation of temporary variable" implemented in our ecoCode rule EC63 : 
- unused variable : https://rules.sonarsource.com/java/tag/unused/RSPEC-1481/
- useless assignment : https://rules.sonarsource.com/java/tag/unused/RSPEC-1854
- immediately return : https://rules.sonarsource.com/java/RSPEC-1488/

Second thing, all implemented tests show that our EC63 rule is a duplication of 3 previous native Sonarqube rules : in each line of test files that we check if we have an issue reported by our rule, there is also a native Sonarqube rule that reports also an issue.

maybe we can use "ecocode" tag to native SaonrQube rules with our tool : https://github.com/green-code-initiative/ecoCode-common/tree/main/tools/rules_config#tagging-scripts

for me, we can deprecate this rule, now. OK with me ?

2023-12-10 21:33 UTC, dedece35 commented
draft : waiting for https://github.com/green-code-initiative/ecoCode/pull/258

2023-12-11 09:41 UTC, dedece35 commented
Hi @natixis-caen and @utarwyn,
as https://github.com/green-code-initiative/ecoCode/pull/258 has been merged to deprecate rule EC63, this PR is closed without merging.

2023-12-11 09:41 UTC, closed without merging