Allow creation of language-specific metadata files
green-code-initiative/ecoCode pull request #242
Opened 2023-11-21 00:01 UTC by utarwyn

This PR adds the ability to create language-specific metadata files (an idea discussed during previous weekly meeting).
The main objective is to precise some informations about a rule for a specific language.

Let's take an example. If I want to deprecate EC4 but only for Java language, I can create the file `src/main/rules/EC4/java/EC4.json` with the following content.

```json
{
  "status": "deprecated"
}
```

This json file **will be merged** during build with the one in the rule root folder. So the result for java/EC4 in the built jar will be:

```json
{
  "title": "Avoid using global variables",
  "type": "CODE_SMELL",
  "status": "deprecated",
  "remediation": {
    "func": "Constant\/Issue",
    "constantCost": "5min"
  },
  "tags": [
    "performance",
    "eco-design",
    "ecocode"
  ],
  "defaultSeverity": "Minor"
}
```

The script also allows to create new JSON keys for a specific language (if we want to add a description or something else).

2023-11-28 20:24 UTC, dedece35 requested changes
sorry @utarwyn, but I don't understand why you want to merge 2 files.

Why can't we update directly the EC4.json of rules-specifications with "status: deprecated" instead of merging several files ?
We can make a technical meeting if you want to talk about it.

2023-11-28 22:15 UTC, utarwyn commented
> @dedece35 
> sorry utarwyn, but I don't understand why you want to merge 2 files.
> 
> Why can't we update directly the EC4.json of rules-specifications with "status: deprecated" instead of merging several files ? We can make a technical meeting if you want to talk about it.

In the current way of working, we can only configure a single metadata file (json) for a dedicated rule (for example, a single EC4.json for all languages). The problem we have is that if we want to deprecate EC4 **only for Java**, we can't.. because we'd also be deprecating the rule in the other languages.

So we need a way of proposing overloads for certain languages: that's what I'm doing in this PR with the JSON merge, as proposed by @jycr during a weekly metting. The objective is to keep a single metadata file in most cases, but to be able to deprecate a rule or change the remediation time for a single language, for example.

2023-11-29 20:38 UTC, dedece35 commented
> > @dedece35
> > sorry utarwyn, but I don't understand why you want to merge 2 files.
> > Why can't we update directly the EC4.json of rules-specifications with "status: deprecated" instead of merging several files ? We can make a technical meeting if you want to talk about it.
> 
> In the current way of working, we can only configure a single metadata file (json) for a dedicated rule (for example, a single EC4.json for all languages). The problem we have is that if we want to deprecate EC4 **only for Java**, we can't.. because we'd also be deprecating the rule in the other languages.
> 
> So we need a way of proposing overloads for certain languages: that's what I'm doing in this PR with the JSON merge, as proposed by @jycr during a weekly metting. The objective is to keep a single metadata file in most cases, but to be able to deprecate a rule or change the remediation time for a single language, for example.

It's clearer now, thank you.
But ... : 
- maybe we can describe this process in documentation
- I didn't test your PR, do you test it in real environment ? if yes, ok for me, maybe ask for a review at @jycr because he created this feature at the beginning

2023-11-29 22:36 UTC, utarwyn commented
@dedece35 
Thank you for the feedback! I have updated the README file with some explanation of the files structure. I have tested to deprecate rule EC4 on my local installation and this works well (like the example I used above).

I agree to wait for review of @jycr.

2023-12-01 21:27 UTC, dedece35 submitted a review, later dismissed

2023-12-04 18:18 UTC, jycr commented
I think the needed dependency definitions can be improved to be specific to running the jshell plugin.
Also, we can use the standard JSON manipulation API ([JSON-P - JSR 374](https://javaee.github.io/jsonp/)) which offers a method for merging JSON.
You can see my PR on your PR :)
-> https://github.com/green-code-initiative/ecoCode/pull/254

2023-12-04 18:19 UTC, jycr requested changes
I think the needed dependency definitions can be improved to be specific to running the jshell plugin.
Also, we can use the standard JSON manipulation API ([JSON-P - JSR 374](https://javaee.github.io/jsonp/)) which offers a method for merging JSON.
You can see my PR on your PR :)
-> https://github.com/green-code-initiative/ecoCode/pull/254

2023-12-04 18:23 UTC, utarwyn commented
> @jycr 
> I think the needed dependency definitions can be improved to be specific to running the jshell plugin. Also, we can use the standard JSON manipulation API ([JSON-P - JSR 374](https://javaee.github.io/jsonp/)) which offers a method for merging JSON. You can see my PR on your PR :)

Thank you for the improvements! Let me look at this and re-check with your improvements if its working well

2023-12-04 20:59 UTC, dedece35 approved these changes

2023-12-04 21:53 UTC, jycr approved these changes

2023-12-04 23:24 UTC, merged