Update the SonarQube version in README.md
green-code-initiative/ecoCode pull request #27
Opened 2022-12-27 10:31 UTC by oussamaLaribi

Update the SonarQube version in README.md after the upgrade.

2023-01-02 22:54 UTC, dedece35 approved these changes

2023-01-02 22:55 UTC, dedece35 requested changes
please add a new comment in changelog, in part "unreleased" please

2023-01-03 08:35 UTC, oussamaLaribi commented
> please add a new comment in changelog, in part "unreleased" please

Hi @dedece35, Okay I'll do it. Thanks.

2023-01-03 09:52 UTC, dedece35 approved these changes

2023-01-03 09:52 UTC, merged