Ajout règles 69, 72 et 75 pour C#
green-code-initiative/ecoCode pull request #278
Opened 2024-03-12 20:18 UTC by Djoums

2024-03-12 20:33 UTC, dedece35 requested changes
cf les commentaires directement dans le code + il manque les éléments suivants pour que ça fonctionne : 
- update le fichier "README.md" avec un exemple CSHARP
- ajouter un fichier "csharp.xml" dans "src/main/assembly" sur le même modèle que les autres langages décrivant le template des fichiers à prendre en compte
- update du "pom.xml" pour rajouter la référence au nouveau fichier "csharp.xml" du répertoire "assembly" ... et aussi sur le même modèle que les autres langages
- la mise à jour du fichier "RULES.md" avec une nouvelle colonne C# + remplissage des règles implémentées (et voir si tu remarque d'autres règles dispo dans le tableau qu'on pourrait implémenter en C#) => ce fichier est à mettre à jour en attendant qu'on sorte notre site web (basé sur ecocode-rules-specifications) afin d'avoir un référentiel de règles dynamique

2024-03-12 20:46 UTC, Djoums commented on ecocode-rules-specifications/src/main/rules/EC75/cs/EC75.asciidoc
> +== Why is this an issue ?
Oui, je découvre le format 😅

2024-03-12 21:11 UTC, Djoums commented
Ok j'ai corrigé tes retours, j'ai fait au jugé

2024-03-12 21:22 UTC, dedece35 requested changes

2024-03-12 21:22 UTC, dedece35 commented on RULES.md
> +| EC75     | Don't concatenate strings in loops                                                                         | Consider calling the function once before the loop and caching the result
EC75 c'est non implémentable pour JAVA ... cf le tableau tout en bas sur les règles supprimées
pour les autres ... on ne sait pas si implémentabel ou pas, si bonne idée ou pas ... perso, j'aurai mis un nouvel icone "?" (avec la légende en haut) expliquant qu'il faut étudier le besoin

2024-03-12 21:22 UTC, dedece35 commented on RULES.md
> -| EC75     | Java     | Concatenate Strings in loop                 | Optimizations on Java concatenation Strings are useless since JDK8                                                           | [G
à laisser ici pour le Java car explication dans le lien fourni avec

2024-03-12 21:22 UTC, dedece35 commented on ecocode-rules-specifications/pom.xml
> +								<descriptor>${project.basedir}/src/main/assembly/charp.xml</descriptor>
il manque un "s" au nom du fichier "charp.xml" :p

2024-03-13 07:12 UTC, Djoums commented on RULES.md
> -| EC75     | Java     | Concatenate Strings in loop                 | Optimizations on Java concatenation Strings are useless since JDK8                                                           | [G
J'ai remis

2024-03-13 07:13 UTC, Djoums commented on RULES.md
> +| EC75     | Don't concatenate strings in loops                                                                         | Consider calling the function once before the loop and caching the result
Ok j'ai trouvé le glyphe qui va bien 😉

2024-03-13 20:37 UTC, dedece35 approved these changes

2024-03-14 07:54 UTC, merged