Added Swift version of rule EC513
green-code-initiative/ecoCode pull request #294
Opened 2024-04-30 07:40 UTC by zippy1978

A port of EC513 rule.
This rule already exists for Android / Java.

Addresses issue https://github.com/green-code-initiative/ecoCode/issues/293

2024-05-13 20:28 UTC, dedece35 submitted a review, later dismissed

2024-05-17 12:30 UTC, zippy1978 commented
@dedece35 conflicts resolved :)

2024-05-20 20:01 UTC, dedece35 requested changes

2024-05-20 20:01 UTC, dedece35 commented on CHANGELOG.md
> +- [#18](https://github.com/green-code-initiative/ecoCode-csharp/issues/18) [EC81] [C#] Specify struct layout
another duplication to correct, please

2024-05-30 19:12 UTC, dedece35 approved these changes

2024-05-30 19:14 UTC, dedece35 approved these changes

2024-05-30 19:15 UTC, merged