EC92
green-code-initiative/ecoCode pull request #342
Opened 2024-06-13 06:25 UTC by Batsh028

Added

-EC92 folder with json file and asciidoc

Changed

-CHANGELOG.md and RULES.md

2024-06-13 06:40 UTC, Djoums commented on CHANGELOG.md
> +- [C# #67](https://github.com/green-code-initiative/ecoCode-csharp/pull/54) [EC92] [C#] Use string.Length instead of comparison with empty string
Fusionne les 2 blocs added

2024-06-13 06:44 UTC, dedece35 requested changes

2024-06-13 06:44 UTC, dedece35 commented on RULES.md
> +| EC89     | Avoid using function cache without limit                      | If a function has decorators without max size cache, the program will store unlimited datas
why do you delete others colums at the end of this line ?

2024-06-13 19:03 UTC, dedece35 submitted a review, later dismissed

2024-06-13 20:05 UTC, dedece35 commented
Hi @Batsh028,
sorry but could you correct the conflict, please ?

2024-06-14 07:56 UTC, Djoums approved these changes

2024-06-14 07:58 UTC, Djoums approved these changes

2024-06-14 07:59 UTC, merged