Update plugin description in code issue #33 :
green-code-initiative/ecoCode pull request #43
Opened 2023-01-11 13:59 UTC by oussamaLaribi

-Add homepage URL
 -Fix organization
 -Fix organization URL
 -Add minimal JRE Specification Version

2023-01-14 21:40 UTC, dedece35 commented
Hi @oussamaLaribi ,

please correct the failed checks phase.
thank you.

2023-01-16 08:46 UTC, oussamaLaribi commented
> Hi @oussamaLaribi ,
> 
> please correct the failed checks phase. thank you.
Hi @dedece35, 
I don't know why the sonar failed maybe I don't have permission from the new organization. Thanks.

2023-01-18 15:38 UTC, dedece35 reviewed
why do you have to need to do this modification ?
I corrected the problem of external PR checks, yesterday .... and it's ok now

for me, non need to modify this github action

2023-01-18 15:42 UTC, dedece35 requested changes

2023-01-18 15:44 UTC, oussamaLaribi commented
> why do you have to need to do this modification ? I corrected the problem of external PR checks, yesterday .... and it's ok now
> 
> for me, non need to modify this github action

Hi @dedece35, yes I saw it, its ok for me too thanks, I have reverted the changes the other modification is related to issue #33

2023-01-18 15:48 UTC, dedece35 commented
> > why do you have to need to do this modification ? I corrected the problem of external PR checks, yesterday .... and it's ok now
> > for me, non need to modify this github action
> 
> Hi @dedece35, yes I saw it, its ok for me too thanks, I have reverted the changes the other modification is related to issue #33

Hi @oussamaLaribi, ok. sorry, my bad, I saw that it's a revert and not an update :p after writing my comment :(

2023-01-18 15:49 UTC, oussamaLaribi commented on java-plugin/pom.xml
> +                    <jreMinVersion>${java.version}</jreMinVersion>
No, we don't have a problem. It's just a lack of information
Minimal JRE Specification Version: empty
When we build the plugin, mentioned in  #33

2023-01-18 15:49 UTC, oussamaLaribi commented on php-plugin/pom.xml
> +                    <jreMinVersion>${java.version}</jreMinVersion>
same as the java part also

2023-01-18 15:49 UTC, oussamaLaribi commented on python-plugin/pom.xml
> +                    <jreMinVersion>${java.version}</jreMinVersion>
Same as the java part also

2023-01-18 15:52 UTC, oussamaLaribi commented
> > > why do you have to need to do this modification ? I corrected the problem of external PR checks, yesterday .... and it's ok now
> > > for me, non need to modify this github action
> > 
> > 
> > Hi @dedece35, yes I saw it, its ok for me too thanks, I have reverted the changes the other modification is related to issue #33
> 
> Hi @oussamaLaribi, ok. sorry, my bad, I saw that it's a revert and not an update :p after writing my comment :(

Alright, thanks anyway.

2023-01-18 20:02 UTC, dedece35 commented on java-plugin/pom.xml
> +                    <jreMinVersion>${java.version}</jreMinVersion>
ok

2023-01-18 20:02 UTC, dedece35 commented on php-plugin/pom.xml
> +                    <jreMinVersion>${java.version}</jreMinVersion>
ok

2023-01-18 20:02 UTC, dedece35 commented on python-plugin/pom.xml
> +                    <jreMinVersion>${java.version}</jreMinVersion>
ok

2023-01-18 20:02 UTC, dedece35 approved these changes

2023-01-18 20:04 UTC, dedece35 commented
Hi @oussamaLaribi,
PR approved ! 
you can merge with squash option and small comment, please.

2023-01-18 21:05 UTC, merged